### ISSUE TITLE
channel order using readMef3

### ISSUE THREAD

**Issue by dorahermes** [MaxvandenBoom/matmef#1]
There is an issue when I use readMef3 to only load the metadata. When I use the following code, the metadata are sorted according to the acquisition channel number and correctly match the signaldata file.
`[metadata,signaldata] = readMef3(fileName);`

However, when I use readMef2 to only load the metadata (as below), the metadata are not sorted according to the acquisition channel number to match the signaldata file.
`[metadata] = readMef3(fileName);`

**Comment by MaxvandenBoom** [comment]
Yes indeed, thank you!
Has been fixed with the last commit b5b15056ffafb1069e982d36eed453017264ebb3
