### ISSUE TITLE
Issue with Mac

### ISSUE THREAD

**Issue by arnodelorme** [MaxvandenBoom/matmef#2]
Using Dora's file "sub-01_ses-ieeg01_task-ccep_run-01_ieeg.mefd"

[metadata,] = readMef3('sub-01_ses-ieeg01_task-ccep_run-01_ieeg.mefd');

This function never returns

Upon trying to recompile (osx 14.4 Matlab 2020a) I get this error

```
Building with 'Xcode with Clang'.
Error using mex
/data/matlab/eeglab/plugins/matmef/matmef_mapping.c:1218:61: error: no member named 'type' in 'MEFREC_Epoc_1_0'
                mxSetField(mat_epoc, 0, "type",                                         mxCreateString(epoc->type));
                                                                                                       ~~~~  ^
1 error generated.
```

**Comment by MaxvandenBoom** [comment]
Hi Arnaud,

Compiling was indeed broken after last week's update of the upstream meflib, forgot to update a variable-name, that is fixed now. I'll test dora's data-set tomorrow!

**Comment by MaxvandenBoom** [comment]
@arnodelorme I looked at the dataset on OSF and it was not complete yet, now it is.

If you download the dataset again (https://osf.io/vmxdn/) then the read function:
`[meta, date] = readMef3('/BIDS_MotorAmp/sub-01/ses-ieeg01/ieeg/sub-01_ses-ieeg01_task-finger_run-1234_ieeg.mefd');`
should work perfectly. Also, it would be good to pull matmef again from this repository, I psuhed some updates yesterday.

Let me know if it works for you now!

**Comment by arnodelorme** [comment]
Yes it did work
